version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN: "true" # <-- ADD THIS LINE
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  pulse-ingest:
    build:
      context: . # Use the project root as context
      dockerfile: ./services/pulse-ingest/dockerfile # Specify path to Dockerfile
    container_name: pulse-ingest
    ports:
      - "8000:8000"
    env_file:
      - ./services/pulse-ingest/.env
    depends_on:
      - kafka

  pulse-content-api:
    build:
      context: . # Use the project root as context
      dockerfile: ./services/pulse-content-api/dockerfile # Specify path to Dockerfile
    container_name: pulse-content-api
    ports:
      - "8001:8001"
    env_file:
      - ./services/pulse-content-api/.env
    depends_on:
      - kafka
      - opensearch

volumes:
  opensearch-data:
