FROM python:3.11-slim
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
WORKDIR /code

COPY ./services/pulse-ingest/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./libs/common_models /code/libs/common_models
RUN pip install -e /code/libs/common_models

COPY ./services/pulse-ingest/app /code/app
COPY ./services/pulse-ingest/test_data /code/test_data

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]