FROM python:3.11-slim
WORKDIR /code

# Copy requirements file for the specific service
COPY ./services/pulse-ingest/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copy the shared library
COPY ./libs/common_models /code/libs/common_models

# Install the shared library so Python can find it
RUN pip install -e /code/libs/common_models

# Copy the application code for the specific service
COPY ./services/pulse-ingest/app /code/app

COPY ./services/pulse-ingest/test_data /code/test_data

# Command to run the application
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
