FROM python:3.11-slim
WORKDIR /code

COPY ./services/pulse-email-service/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./services/pulse-email-service/app /code/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8004"]