FROM python:3.11-slim
WORKDIR /code

COPY ./services/pulse-agent-manager/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./libs/common_models /code/libs/common_models
RUN pip install -e /code/libs/common_models

COPY ./services/pulse-agent-manager/app /code/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8003"]